name: Build and push inkscape image

on:
  push:
    paths: 
      - 'engine/inkscape/**'
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u  ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: create Tags
        if: ${{ github.ref != 'refs/heads/master' }}
        run: echo "INKSCAPE_TAG=topiaas/inkscape:${{ github.sha }}" >> $GITHUB_ENV
        
      - name: create latest
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "INKSCAPE_TAG=topiaas/inkscape:${{ github.sha }},topiaas/inkscape:latest" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: engine/inkscape/Dockerfile.inkscape
          context: engine/inkscape/
          push: true
          tags: ${{ env.INKSCAPE }}
          
      - name: prune
        run: docker system prune -a -f
